# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ImageMagick & headers
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick libmagickwand-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'

      - name: Enable bundler cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install deps
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install -g mermaid.cli

      - name: Setup deploy options
        id: setup
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
            echo "NO_PUSH=--no-push"       >> $GITHUB_OUTPUT
          else
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

      - name: Deploy website
        run: |
          yes | bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
                          --src ${{ steps.setup.outputs.SRC_BRANCH }} \
                          --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
